lr: 0.0000839
horizon: ${experiment.horizon}
lookback: 720
ne_blocks: 1
nd_blocks: 1
hidden_size: 1024
dropout_level: 0.5
covariates_size: 4
temporal_decoder_hidden_size: 128
decoder_output_size:  ${mul:8,${.horizon}}
static_covariates_size: 1
max_epochs: 10
feature_projection_output_size: ${.covariates_size}
feature_projection_hidden_size: ${.covariates_size}
train_size: 0.8
train_batch_size: 512
test_batch_size: 512
layer_norm: true